### ISSUE TITLE
TypeScript definition is not published

### ISSUE THREAD

**Issue by lacolaco** [phrase/ngx-translate-phraseapp#1]
`ngx-translate-phraseapp` npm package doesn't contain its own TypeScript type definition. 

![image](https://user-images.githubusercontent.com/1529180/40759695-268c1200-64ce-11e8-8130-37a0ddfa5ab3.png)

![image](https://user-images.githubusercontent.com/1529180/40759712-3a50a332-64ce-11e8-946d-9d0767c830a7.png)

**Comment by theSoenke** [comment]
Hi, I will look into adding the type definitions. Do you use any settings that enforce the usage of type definitions? For example our demo project works fine without the type definitions https://github.com/phrase/ngx-translate-phraseapp-demo

**Comment by theSoenke** [comment]
@lacolaco I just published version 0.1.6. This release now should contain the Typescript type definitions. Let me know if you should still see any issues

**Comment by lacolaco** [comment]
@theSoenke I've update version and it works perfectly! Thanks!

**Comment by mikyaj** [comment]
@theSoenke I am facing same issue with version 0.3.0

**Comment by theSoenke** [comment]
Hi @mikyaj, I was able to reproduce it myself and I'm looking into it

**Comment by FRSgit** [comment]
Hello @mikyaj! Could you please share your project's config (especially `tsconfig.json`)?
I want to make sure that your case is covered by the fix I've just written

**Comment by mikyaj** [comment]
Here you go @FRSgit 
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "downlevelIteration": true,
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2015",
    "resolveJsonModule": true,
    "esModuleInterop": true  ,
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  }
}
```

**Comment by FRSgit** [comment]
Hey @mikyaj! I'm sorry that it took so long. I've just released new version of the package (`0.4.1`) and it should resolve the issue you're facing. Can you check it please? ✌️

**Comment by mikyaj** [comment]
Hi @FRSgit It works fine now. I hace checked. Thanks.

**Comment by FRSgit** [comment]
@mikyaj Thank you for testing my fix 💪 Glad to hear that it works now! Sorry that you needed to wait for so long - I needed to make few more adjustments to make this change possible.
Feel free to contact us whenever you need to, have a good one! 👌
