### ISSUE TITLE
Slotted elements not picked up by In-Context Editor

### ISSUE THREAD

**Issue by niklaskappler** [phrase/ngx-translate-phraseapp#19]
Hi,
I just found a bug in the In-Context Editor itself and because the editor is not open source itself I'm opening this issue here.
The problem is that the editors, document parser is not registering translations properly when they are slotted into a web component. This is happening when using a non named / default slot and providing the slot's content only as text node(not wrapped within another html element).

I guess, reason for this is inside the `processInlineText` function in the `document_parser.ts` of the In-Context Editor itself. 
In case the web components top-level child node contains a text node, it will be skipped because of the following if switch.
```
    processInlineText(elem) {
        ...
        Array.from(elem.shadowRoot
            ? elem.shadowRoot.childNodes
            : elem.childNodes).forEach((element) => {
            ...
```
 In case of a shadowRoot present it should merge `elem.shadowRoot.childNodes` with (in case present) text nodes from `elem.childNodes`. I did set up an example in the demo repo: https://github.com/niklaskappler/ngx-translate-phraseapp-demo/tree/webcomponents-bug

**Comment by niklaskappler** [comment]
@docstun can somebody have a look at this?

**Comment by theSoenke** [comment]
Hey @niklaskappler, thanks for already investigating this and providing an example. We're now taking a closer look at this and I'll keep you updated when there are any news

**Comment by sbruhns** [comment]
Hi @niklaskappler, we fixed the issue and released a new version of the in_context_editor. Just reloading will fetch the latest version of In-Context Editor, so no update of any npm package is needed.

We verified this with your example:
![Selection_168](https://user-images.githubusercontent.com/5496983/107025781-2c48c580-67aa-11eb-9af7-5325c2906893.png)
