### ISSUE TITLE
Only first letter regonized as key + Typing to form elements not possible

### ISSUE THREAD

**Issue by daheadcracker** [phrase/ngx-translate-phraseapp#46]
Hi,
I just upgraded from version 0.x to` "ngx-translate-phraseapp": "^1.1.2"` . 

Setup:
angular: 15.2.8
@ionic/angular: 6.7.1

I'm facing 2 issues:

1. Keys are not picked up correctly. Only the first letter of the key is showing and I think therefore it wants to create new keys allthough all keys are already synced with phrase.
![image](https://github.com/phrase/ngx-translate-phraseapp/assets/3524490/8eb44242-9292-4a93-b978-8eb52f599955)
![image](https://github.com/phrase/ngx-translate-phraseapp/assets/3524490/7c8e76a3-5196-4aad-a841-e2ded7f728c7)

2. With version 0 we "only" had the issue that editing of the strings wasn't possible on modals because the focus of the cursor was always jumping somewhere into the modal. This issue is worse now in version 1. Now also in the e.g. the root view I'm not able to click on any input form to type. Not the search bar nor within the phrase modal that pops up to edit a translation -> no cursor!
![image](https://github.com/phrase/ngx-translate-phraseapp/assets/3524490/efe7185e-1ee8-48a6-bf7b-284c56316884)
![image](https://github.com/phrase/ngx-translate-phraseapp/assets/3524490/b836328f-108e-498e-97d7-e7dc6a4d21b3)

**Comment by daheadcracker** [comment]
Setting the config to `useOldICE: true,` leads also to picking up no keys at all. Clicking the editing buttons on the page next to the keys/translations is not doing anything in the translation overlay. No console errors either.
![image](https://github.com/phrase/ngx-translate-phraseapp/assets/3524490/cf995b62-8251-45cf-9ec4-f114370f913f)
![image](https://github.com/phrase/ngx-translate-phraseapp/assets/3524490/3d7dae02-b154-47f8-acdc-a9029cad7a7d)

**Comment by daheadcracker** [comment]
Was able to kinda fix the 2. issue on the root view with this parameter:
`fullReparse: false,`
![image](https://github.com/phrase/ngx-translate-phraseapp/assets/3524490/80c68519-9fb3-469a-a1ff-5d962b869e4a)

The issue like in v0 still persists in modals. Still not able type to the input elements of phrase if any angular modal of the app is opened.
![image](https://github.com/phrase/ngx-translate-phraseapp/assets/3524490/35581982-8536-4cb9-a23a-7b17a78dfc0f)

**Comment by daheadcracker** [comment]
I could fix the first issue by removing the config parameters:

```
prefix: "",
suffix: "",
```

These parameter seem to be only relevant in version 0.
The second issue persists.

**Comment by itsahsiao** [comment]
Hi @daheadcracker, thanks a lot for reporting this. We'll have to adjust the config properly to reflect the latest version and look into the issue with the modal and inputs.

**Comment by itsahsiao** [comment]
@daheadcracker We have this planned in our current sprint and will have a look within the next weeks. Will keep you posted!

**Comment by flowreaction** [comment]
Hi @daheadcracker, I am having difficulty reproducing this, could you maybe share some of your setup or create a reproduciton repository with our Demo Phrase project which has these credentials:
```ts
projectId: '00000000000000004158e0858d2fa45c',
accountId: '0bed59e5',
```
login with user: `demo@phrase.com` pw: `phrase`

**Comment by daheadcracker** [comment]
Hi @flowreaction, thanks for looking into this. I created a demo repo thats similar to mine:
https://github.com/daheadcracker/phrase-modal-bug

It's using angular 16 / Ionic 7 but the issue is the same. Serve it and click the "open modal" button, then try to add a new key. You will not able write anything to the phrase "new key" modal input boxes because the cursor is jumping somewhere else. Try to add a new key now, without opening the demo modal and there it's working.

**Comment by flowreaction** [comment]
@daheadcracker thanks I will investigate and get back to you asap

**Comment by itsahsiao** [comment]
@daheadcracker We had an initial look recently and it looks like the ionic library might be interfering with the modals and inputs. We need to spend some more time and have another deeper look to see if we can resolve this. Sorry to keep you waiting and we will keep you posted!

**Comment by itsahsiao** [comment]
@daheadcracker Just to keep you posted, this issue is planned in a sprint and we will have another look.

**Comment by daheadcracker** [comment]
Nope, please don't close. Issue is still not resolved.

**Comment by Varpusparvi** [comment]
@daheadcracker I took a look on the modal issue and had some findings.

Ionic has this [modal focus trapping](https://ionicframework.com/docs/api/modal#focus-trapping) on card type modals that seemingly can't be disabled, but on [sheet type modals](https://ionicframework.com/docs/api/modal#sheet-modals) this can be worked around with `backdropBreakpoint`. 

Of course the functionality between these types is not the same so can't be direclty interchanged :/

To me this functionality does looks like a feature/restriction in Ionic rather than ICE, since from our side we can't really work around on our side. 

Luckily I have [found](https://github.com/ionic-team/ionic-framework/issues/24646#issuecomment-1538250165) a solution for you 😄 You can use class `ion-disable-focus-trap` on the modal to disable the focus trapping allowing ICE to work with the modals.

```
    let modal: any = await this.modal.create({
      component: ExploreContainerComponent,
      componentProps: {},
      cssClass: "ion-disable-focus-trap",
    });
```
https://github.com/phrase/ngx-translate-phraseapp/assets/44475420/44d7781f-09ea-4f81-83f3-cc2f0b282996

@daheadcracker Please let me know if this helps!
