### ISSUE TITLE
Phrase editor unexpected behaviour when using css class hidden 

### ISSUE THREAD

**Issue by SofieAndersen** [phrase/ngx-translate-phraseapp#63]
**Expected behavior**
CSS 'hidden' should not impact phrase context editor. This is especially an issue when using tailwind css since that is using 'hidden' as a utility class that will be used in combination with a display class for certain breakpoints. 

**Actual behavior**
When using css 'hidden' in combination with other css classes phrase context editor does not pick up the translation and displays the raw `{{__phrase_hero_title__}}` without an option to edit even though the element is full visible

![Screenshot 2024-08-22 at 13 44 22](https://github.com/user-attachments/assets/58ba0005-1141-464e-aea7-8c80f0e6ddf3)

**Your environment**
N/A

**Steps to reproduce the problem**
See: https://stackblitz.com/edit/stackblitz-starters-o6notr

Setup to use 
```
projectId: '00000000000000004158e0858d2fa45c',
accountId: '0bed59e5',
```
login with user: demo@phrase.com pw: phrase

In this example I ended up using the inline js script and a hard coded value. However when using `ngx-translate-phraseapp` the exact same issue occurs. Since the `PhraseAppCompiler` simply transforms all the translations and the translate pipe simple outputs the transformed keys. 

Also mention in: https://github.com/phrase/i18next-phrase-in-context-editor-post-processor/issues/175

**Additionally** 
I noticed a small ui issue with the context editor; when you have multiple translations close to each other the dropdown when editing falls below other edit buttons

![Screenshot 2024-08-22 at 13 42 04](https://github.com/user-attachments/assets/93b5fd9e-4527-4b16-ac95-5586870893c1)

**Comment by itsahsiao** [comment]
HI @SofieAndersen, thank you for reporting this! We'll look into it and see what we can do.

**Comment by lookasc** [comment]
Hi @SofieAndersen, We've resolved this issue, by allowing you to pass a new option to `initializePhraseAppEditor`. 
In version `v1.3.0`, you can do:
```typescript
initializePhraseAppEditor({
  // your options
  hidingClasses: ['custom-hidden'],
});
```
Refer to the description in this [PR](https://github.com/phrase/ngx-translate-phraseapp/pull/65). Keep in mind that by providing your classes you're overriding our defaults - `['hidden', 'visuallyhidden', 'invisible']`. If any of our defaults are applicable in your case, you have to add them to `hidingClasses` as well.
