### ISSUE TITLE
Inaccurate config typings

### ISSUE THREAD

**Issue by json-derulo** [phrase/ngx-translate-phraseapp#64]
**Expected behavior**

When omitting required attributes in the config, such as `projectId` or `accountId`, a type error should be thrown.

**Actual behavior**

No type error is being thrown. For example, the following code builds:

```ts
import { initializePhraseAppEditor } from 'ngx-translate-phraseapp';

initializePhraseAppEditor({});
```

But with this setup, on runtime the following error is thrown:

```
Config is not set up properly
Please set up the PHRASEAPP_CONFIG object with `accountId` and `projectId`, as well as any other needed options.
```

It would be good to catch this already on build time by providing more accurate typings for the config.

**Comment by itsahsiao** [comment]
Hi @json-derulo , thanks for reporting this. We will have a look into this.

**Comment by lookasc** [comment]
Hi @json-derulo, the type has been improved in `v1.3.0`.
